resolver: lts-20.10
extra-deps:
  - hs-opentelemetry-api-0.0.3.6
  - hs-opentelemetry-exporter-otlp-0.0.1.4
  - hs-opentelemetry-instrumentation-persistent-0.0.1.0
  - hs-opentelemetry-instrumentation-wai-0.0.1.3
  - hs-opentelemetry-instrumentation-yesod-0.0.1.3
  - hs-opentelemetry-otlp-0.0.1.0
  - hs-opentelemetry-propagator-w3c-0.0.1.2
  - hs-opentelemetry-sdk-0.0.3.4
  - thread-utils-context-0.2.0.0
  - thread-utils-finalizers-0.1.0.0
